blueprint:
  name: 'Ultimate Heating Control'
  description: 'Automatic heating based on a scheduler, presence of people and optional dependencies such as window opening, winter mode or party mode. Optional calibration using a separate temperature sensor. Forked from panahns'
  source_url: 'https://github.com/clemensao/homeassistant/blob/main/blueprints/automation/heating_control.yaml'
  domain: automation
