blueprint:
  name: "Heating Control"
  description: >
    Automatic heating based on scheduler, presence, night mode, window state and humidity.
    Temperature changes only on relevant state changes or restart – manual thermostat changes remain possible.
    Window has highest priority. Humidity enforces comfort temperature.
    Tado devices are set to "heat" mode to avoid internal schedules.
  source_url: "https://github.com/clemensao/homeassistant/blob/main/blueprints/automation/heating_control.yaml"
  domain: automation
  input:
    thermostats:
      name: "Thermostats / Valves"
      description: "Thermostats to be controlled"
      selector:
        entity:
          domain: climate
          multiple: true

    persons:
      name: "Persons"
      description: "If a person is at home and the schedule is on, the comfort temperature is set."
      selector:
        entity:
          domain:
            - person
            - device_tracker
          multiple: true

    scheduler:
      name: "Scheduler"
      description: "Scheduler that specifies when the comfort temperature can be set. Scheduler can be added in the helpers section in your home assistant settings."
      selector:
        entity:
          domain: schedule
          multiple: false

    night_time:
      name: "Nighttime"
      description: "Sensor that tells it is night time"
      default:
      selector:
        entity:
          domain:
            - binary_sensor
            - input_boolean

    alarm_time:
      name: "Next time the alarm clock rings (optional)"
      description: "Use a sensor for alarm time to determine whether you want to sleep in or work (optional)."
      default:
      selector:
        entity:
          device_class: timestamp

    home_office:
      name: "Working at home (optional)"
      description: "If you use this option, the scheduler is used only when the input is true (optional)."
      default:
      selector:
        entity:
          domain: input_boolean

    winter_mode:
      name: "Wintertime (optional)"
      description: "If this input boolean is off, heating will never occur."
      default:
      selector:
        entity:
          domain: input_boolean

    heat_mode:
      name: "Heat mode (optional)"
      description: "Overwrites winter mode and scheduler. If on, heating is activated."
      default:
      selector:
        entity:
          domain: input_boolean

    window:
      name: "Window (optional)"
      description: "Window that turns off the thermostats if it is open."
      default:
      selector:
        entity:
          domain: binary_sensor

    moisture_threshold:
      name: "Humidity Threshold (optional)"
      description: "A threshold helper reflecting Humidity can be added. If on (humid) it overrides scheduler and presence"
      default:
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
    
    min_temp:
      name: "Eco temperature"
      description: "If no one is at home, the Eco temperature is set."
      default: 18
      selector:
        number:
          min: 5
          max: 25
          step: 0.5
          mode: slider

    min_temp_input:
      name: "Eco temperature input (optional)"
      description: 'If no one is at home, the eco temperature is set by a helper number input. This overrides the "Eco temperature". (optional)'
      default:
      selector:
        entity:
          domain: input_number

    comfort_temp:
      name: "Comfort temperature"
      description: "If someone is at home and the schedule is on, the comfort temperature is set."
      default: 20
      selector:
        number:
          min: 10
          max: 25
          step: 0.5
          mode: slider

    comfort_temp_input:
      name: "Comfort temperature from input (optional)"
      description: 'If someone is at home and the schedule is on, the comfort temperature is set by a helper number input. This overrides the "EcoComfort temperature". (optional)'
      default:
      selector:
        entity:
          domain: input_number

    night_temp_input:
      name: "Night temperatue (optional)"
      description: "The temperature which is set at nighttime, using a helper number input (optional)."
      default:
      selector:
        entity:
          domain: input_number    

    window_open_delay:
      name: "Window reaction time"
      description: "Duration that the window must be open for the thermostats to be turned off."
      default: 15
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider

    window_close_delay:
      name: "Window close delay"
      description: "Duration that the window must be closed for the thermostats to resume."
      default: 60
      selector:
        number:
          min: 0
          max: 120
          step: 1
          mode: slider

variables:
  # thermostats
  thermostats: !input "thermostats"
  valves: "{{ expand(thermostats) | map(attribute='entity_id') | list }}"
  # temperatures
  night_temp: !input "night_temp_input"
  eco_temp: !input "min_temp"
  eco_temp_input: !input "min_temp_input"
  comfort_temp: !input "comfort_temp"
  comfort_temp_input: !input "comfort_temp_input"
  # sensors
  persons: !input "persons"
  persons_home: "{{ expand(persons) | selectattr('state', 'eq', 'home') | list | count }}"
  window: !input "window"
  window_open: "{{ window != none and is_state(window, 'on') }}"
  moisture_sensor: !input "moisture_threshold"
  moisture: "{{ moisture_sensor != none and is_state(moisture_sensor,'on') }}"
  # switches
  scheduler: !input "scheduler"
  winter_mode: !input "winter_mode"
  winter_active: "{{ winter_mode == none or is_state(winter_mode, 'on') }}"
  heat_mode: !input "heat_mode"
  force_heat: "{{ heat_mode != none and is_state(heat_mode, 'on') }}"
  home_office: !input "home_office"
  homeoffice_ok: "{{ home_office == none or (home_office != none and is_state(home_office, 'on')) }}"
  night_time: !input "night_time"
  night: "{{ night_time != none and is_state(night_time, 'on') }}"
  alarm_time: !input "alarm_time"
  pre_alarm_time: >
    {% set pre_alarm = false %}
    {% if alarm_time != none %}
      {% set next_alarm = states(alarm_time) %}
      {% if next_alarm not in ['unknown','unavailable'] and now() >= (as_local(as_datetime(next_alarm)) - timedelta(minutes=45)) %} 
        {% set pre_alarm = true %}
      {% endif %}
    {% endif %}
    {{ night == true and alarm_time != none and pre_alarm }}
  use_scheduler: "{{ alarm_time == none or night == false or pre_alarm_time == true }}"
  heating_enabled: "{{ (winter_active or force_heat) and not window_open }}"

  temperature: >
    {% if ( (is_state(scheduler,'on') and homeoffice_ok and use_scheduler) or force_heat ) and persons_home > 0 or moisture %}
      {{ states(comfort_temp_input) if comfort_temp_input != none else comfort_temp }}
    {% elif night and night_temp_input != none %}
      {{ states(night_temp_input) }}
    {% else %}
      {{ states(eco_temp_input) if eco_temp_input != none else eco_temp }}
    {% endif %}

trigger_variables:
  window_t: !input window
  winter_mode_t: !input winter_mode
  heat_mode_t: !input heat_mode
  moisture_t: !input "moisture_threshold"
  night_time_t: !input night_time
  night_temp_t: !input night_temp_input
  eco_temp_t: !input min_temp_input
  alarm_time_t: !input alarm_time

triggers:
  # home assistant events
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  # schedule state changes
  - trigger: state
    entity_id: !input "scheduler"
    id: schedule
  - trigger: template
    value_template: >
      {%  if alarm_time_t != none %}
        {% set next_alarm = states(alarm_time_t) %}
        {% if next_alarm in ['unknown','unavailable'] or now() < (as_local(as_datetime(next_alarm)) - timedelta(minutes=45)) %} 
          false
        {% else %}
          true
        {% endif %}
      {% else %}
        false
      {% endif %}
    for:
      seconds: 1
    id: schedule
  # peoples presence changes
  - trigger: state
    entity_id: !input "persons"
    id: presence
  # window open
  - trigger: template
    value_template: >-
      {{ window_t != none and is_state(window_t, 'on') }}
    for:
      seconds: !input "window_open_delay"
    id: window_open
  # window closes
  - trigger: template
    value_template: >-
      {{ window_t != none and is_state(window_t, 'off') }}
    for:
      seconds: !input "window_close_delay"
    id: window_close
  # moisture threshold
  - trigger: template
    value_template: >-
      {{ moisture_t != none and is_state(moisture_t, 'on') }}
    for:
      seconds: !input "window_open_delay"
    id: moisture
  - trigger: template
    value_template: >-
      {{ moisture_t != none and is_state(moisture_t, 'off') }}
    for:
      seconds: !input "window_close_delay"
    id: moisture
  # winter_mode changes
  - trigger: template
    value_template: >-
      {{ winter_mode_t != none and is_state(winter_mode_t, 'on') }}
    for:
      seconds: 2
    id: winter
  - trigger: template
    value_template: >-
      {{ winter_mode_t != none and is_state(winter_mode_t, 'off') }}
    for:
      seconds: 2
    id: winter
  # heat mode changes
  - trigger: template
    value_template: >-
      {{ heat_mode_t != none and is_state(heat_mode_t, 'on') }}
    for:
      seconds: 2
    id: "heat"
  - trigger: template
    value_template: >-
      {{ heat_mode_t != none and is_state(heat_mode_t, 'off') }}
    for:
      seconds: 2
    id: "heat"
  # night-time  changes
  - trigger: template
    value_template: >-
      {{ night_time_t != none and is_state(night_time_t, 'on') }}
    for:
      seconds: 2
    id: night
  - trigger: template
    value_template: >-
      {{ night_time_t != none and is_state(night_time_t, 'off') }}
    for:
      seconds: 2
    id: morning
  # temperature inputs change (eco and night)
  #- trigger: template
  #  value_template: >-
  #     {{ night_temp_t != none and states(night_temp_t)|float(0) >0 }}
  #  for:
  #    seconds: 2
  #  id: temp_preset
  #- trigger: template
  #  value_template: >-
  #     {{ eco_temp_t != none and states(eco_temp_t)|float(0) > 0 }}
  #  for:
  #    seconds: 2
  #  id: temp_preset

actions:
  - repeat:
      count: "{{ valves | count }}"
      sequence:
        - service: climate.set_hvac_mode
          target:
            entity_id: "{{ valves[repeat.index-1] }}"
          data:
            hvac_mode: >
              {% set m = device_attr(device_id(valves[repeat.index-1]), 'manufacturer') %}
              {% if heating_enabled %}
                {{ 'heat' if m == 'Tado' else 'auto' }}
              {% else %}
                off
              {% endif %}

        - condition: template
          value_template: "{{ heating_enabled }}"

        # 🌙 set temperature on closing window only at night
        - condition: template
          value_template: >
            {{
              trigger.id not in ['window_open','window_close']
              or
              (trigger.id == 'window_close' and night)
            }}

        - delay: 3

        - service: climate.set_temperature
          target:
            entity_id: "{{ valves[repeat.index-1] }}"
          data:
            temperature: "{{ temperature | float }}"

mode: restart
