blueprint:
  name: Tado temperature offset (robust & safe)
  description: >
    Synchronisiert den Temperatur-Offset eines Tado-Thermostats mit einem externen
    Temperatursensor. Unterstützt minimale Offset-Differenz, Offset-Clamp (-4…+4 °C),
    Failsafe bei ungültigen Sensorwerten sowie einen Cooldown zwischen Updates.
    Tagsüber erfolgt das Update in einem frei konfigurierbaren Minutenintervall,
    nachts maximal alle 2 Stunden.
  domain: automation

  input:
    source_temp_sensor:
      name: Source temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    target_tado:
      name: Target Tado thermostat
      selector:
        entity:
          domain: climate
          integration: tado

    min_offset_delta:
      name: Minimal offset difference (°C)
      description: Minimal difference required to trigger an update
      default: 0.2
      selector:
        number:
          min: 0.0
          max: 2.0
          step: 0.1
          unit_of_measurement: "°C"

    day_interval_minutes:
      name: Daytime update interval (minutes)
      default: 30
      selector:
        number:
          min: 5
          max: 180
          step: 5
          unit_of_measurement: "min"

    cooldown_minutes:
      name: Cooldown between updates (minutes)
      description: Minimal time between two offset updates
      default: 60
      selector:
        number:
          min: 5
          max: 360
          step: 5
          unit_of_measurement: "min"

    trigger_sensor:
      name: Trigger on temperature change
      default: false
      selector:
        boolean:

    night_switch:
      name: Nighttime indicator (optional)
      description: ON = night mode active
      default: null
      selector:
        entity:
          domain:
            - binary_sensor
            - input_boolean

  source_url: https://gist.github.com/clemensao/homeassistant/blob/main/blueprints/automation/tado_temp_offset.yaml

variables:
  target_tado: !input target_tado
  source_temp_sensor: !input source_temp_sensor
  min_offset_delta: !input min_offset_delta
  day_interval_minutes: !input day_interval_minutes
  cooldown_minutes: !input cooldown_minutes
  night_switch: !input night_switch

  tado_temp: "{{ state_attr(target_tado, 'current_temperature') | float(0) }}"
  actual_temp: "{{ states(source_temp_sensor) | float(0) }}"
  current_offset: "{{ state_attr(target_tado, 'offset_celsius') | default(0) | float }}"

  raw_offset: "{{ (actual_temp - tado_temp) | round(1) }}"
  calculated_offset: >
    {{ [ [ raw_offset, -4.0 ] | max, 4.0 ] | min }}

  offset_delta: "{{ (calculated_offset - current_offset) | abs }}"

  source_valid: >
    {{ states(source_temp_sensor) not in ['unknown', 'unavailable']
       and actual_temp > 0 }}

  tado_valid: >
    {{ state_attr(target_tado, 'current_temperature') is not none
       and tado_temp > 0 }}

  is_day: "{{ night_switch == none or is_state(night_switch, 'off') }}"

  last_run: "{{ this.attributes.last_triggered }}"
  cooldown_ok: >
    {{ last_run is none
       or (as_timestamp(now()) - as_timestamp(last_run))
          >= cooldown_minutes * 60 }}

trigger:
  # Optional sensor-based trigger
  - platform: state
    entity_id: !input source_temp_sensor
    enabled: !input trigger_sensor

  # Periodic trigger (every minute, filtered by conditions)
  - platform: time_pattern
    minutes: "/1"
    id: periodic

  # Nighttime trigger (every 2 hours)
  - platform: time_pattern
    hours: "/2"
    id: night

condition:
  # Tado must not be off
  - condition: not
    conditions:
      - condition: state
        entity_id: !input target_tado
        state: "off"

  # Failsafe + minimal delta
  - condition: template
    value_template: >
      {{ source_valid
         and tado_valid
         and offset_delta >= min_offset_delta }}

  # Cooldown
  - condition: template
    value_template: "{{ cooldown_ok }}"

  # Trigger logic
  - condition: or
    conditions:
      # Daytime periodic trigger
      - condition: template
        value_template: >
          {{ is_day
             and trigger.id == 'periodic'
             and (now().minute % day_interval_minutes == 0) }}

      # Nighttime trigger
      - condition: template
        value_template: >
          {{ not is_day and trigger.id == 'night' }}

      # Immediate sensor trigger
      - condition: template
        value_template: >
          {{ trigger_sensor and trigger.platform == 'state' }}

action:
  - service: system_log.write
    data:
      logger: blueprints.tado.offset
      level: info
      message: >
        Setting Tado offset for {{ target_tado }} to {{ calculated_offset }} °C
        (raw {{ raw_offset }} °C, delta {{ offset_delta }} °C)

  - service: tado.set_climate_temperature_offset
    data:
      entity_id: "{{ target_tado }}"
      offset: "{{ calculated_offset }}"

mode: single
