blueprint:
  name: 'Temperature Light'
  description: 'Light is changing its color depending on the temperature of a given sensor. <br /> The colors are set by names taken from <a>https://veli.ee/smartcolors/</a>.'
  source_url: 'https://github.com/clemensao/homeassistant/blob/main/blueprints/automation/temperature_light.yaml'
  domain: automation
  input:
    temperature:
      name: 'Temperature-Sensor'
      description: 'Any temperature sensor'
      selector:
        entity:
          domain: sensor
          device_class: temperature
    lights:
      name: 'Lights'
      description: 'Lights which change the color'
      selector:
        entity:
          domain: light
          multiple: true
    switch:
      name: 'Switch (optional)'
      description: 'A boolen input (can be configured in the helper section) to switch the behaviour on and off (optional).'
      default:
      selector:
        entity:
          domain: input_boolean

trigger_variables:
  switch: !input 'switch'
  temp_sensor: !input 'temperature'

trigger:
  # home assistant events
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  # light changes to on
  - platform: state
    entity_id: !input 'lights'
    to: "on"
  # temperature changes
  - platform: state
    entity_id: !input 'temperature'
  - platform: state
    entity_id: !input 'switch'
    to: "on"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: !input 'lights'
        state: "on"
      - condition: template
        value_template: "{{ switch != none and is_state(switch, 'on') }}"
action:
  - service: light.turn_on
    data:
      color_name: >
        {% set colors = [ ('-50','-15','magenta'),
                          ('-15','-10','blueviolet'),
                          ('-10','-5','blue'),
                          ('-5','0','dodgerblue'),
                          ('0','5','cyan'),
                          ('5','10','springgreen'),
                          ('10','15','lawngreen'),
                          ('15','20','yellow'),
                          ('20','25','gold'),
                          ('25','30','darkorange'),
                          ('30','35','orangered'),
                          ('35','50','red') ] %}
        {% set actual_temp = states(temp_sensor)|default(0)|float %} 
        {% for item in colors %}
          {% if actual_temp >= item[0]|float and actual_temp < item[1]|float %}
            {% set color = item[2] %}
            {{ color }}
          {% endif %}
        {% endfor %}
    target:
      entity_id: !input 'lights'